### ISSUE TITLE
How to disable winbar?

### ISSUE THREAD

**Issue by DrKGD** [Hashino/doing.nvim#7]
As I use a custom winbar plugin, I'd like to disable the winbar component of this plugin.

The `enabled` key in the `winbar` configuration dictionary has no effect
```lua
winbar = { 
  enabled = false,
},
```

But the following works
```lua
winbar = false 
```

https://github.com/Hashino/doing.nvim/blob/febad9f3f95a94ededdf30d3dcff1ff8b087384e/lua/doing/api.lua#L19

I suppose it should've been `state.options.winbar.enabled`?
Thanks!

**Comment by Hashino** [comment]
you're right that it should be `state.options.winbar.enabled`. but redrawing the winbar should have no effect if it is disabled.
I also use a different plugin to my winbar and I disable the native winbar of doing. so it should be disabled if you set `winbar.enabled = false`

**Comment by Hashino** [comment]
can you give me a minimal config that reproduces the behaviour? wasn't able to reproduce it. when I set winbar.enabled to false it works as expected (ie: no winbar)

**Comment by DrKGD** [comment]
I suppose its all due to the wrong key being checked
Here, you missed one :laughing:

https://github.com/Hashino/doing.nvim/blob/2f86dd9833bed9936f49176adf1c7427a7cc57a0/lua/doing/core.lua#L76-L79

**Comment by Hashino** [comment]
still doesn't explain why it behaves properly in my system and why I can't reproduce your issue

**Comment by DrKGD** [comment]
Not really sure what do you mean, I suppose my winbar is overriden by this function, which check for the wrong dictionary key, otherwise I have no issues whatsoever with the winbar, it doesn't behave _unpredictably_  so to speak

https://github.com/Hashino/doing.nvim/blob/febad9f3f95a94ededdf30d3dcff1ff8b087384e/lua/doing/core.lua#L76-L95
